//! Interrupt Descriptor Table + Rust interrupt dispatcher.
//!
//! Hand-written asm stubs (isr_stubs.S) push GP registers and call
//! `common_handler(vector, regs)`. This is stable-Rust friendly (no
//! nightly `abi_x86_interrupt`) and keeps full control in-house.

use core::arch::asm;

use super::gdt;
use super::keyboard;
use super::pic;
use super::pit;

#[repr(C)]
pub struct Regs {
    pub rax: u64,
    pub rbx: u64,
    pub rcx: u64,
    pub rdx: u64,
    pub rsi: u64,
    pub rdi: u64,
    pub rbp: u64,
    pub r8: u64,
    pub r9: u64,
    pub r10: u64,
    pub r11: u64,
    pub r12: u64,
    pub r13: u64,
    pub r14: u64,
    pub r15: u64,
    // pushed by stub after GP regs:
    pub error_code: u64,
    pub rip: u64,
    pub cs: u64,
    pub rflags: u64,
    pub rsp: u64,
    pub ss: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Entry {
    off_lo: u16,
    sel: u16,
    ist: u8,
    attr: u8,
    off_mid: u16,
    off_hi: u32,
    rsv: u32,
}

impl Entry {
    const MISSING: Entry = Entry {
        off_lo: 0,
        sel: 0,
        ist: 0,
        attr: 0,
        off_mid: 0,
        off_hi: 0,
        rsv: 0,
    };

    fn set(&mut self, handler: usize) {
        *self = Entry {
            off_lo: handler as u16,
            sel: gdt::KERNEL_CODE,
            ist: 0,
            attr: 0x8E, // present, ring0, interrupt gate
            off_mid: (handler >> 16) as u16,
            off_hi: (handler >> 32) as u32,
            rsv: 0,
        };
    }
}

#[repr(C, align(16))]
struct Idt {
    entries: [Entry; 256],
}

static mut IDT: Idt = Idt {
    entries: [Entry::MISSING; 256],
};

#[repr(C, packed(2))]
struct Ptr {
    limit: u16,
    base: u64,
}

// stub symbols generated by isr_stubs.S, vectors 0..=47 in order
macro_rules! isr_stubs {
    ($($sym:ident),* $(,)?) => {
        extern "C" {
            $(static $sym: u8;)*
        }
        fn stub_addrs() -> [usize; 48] {
            unsafe { [ $( &$sym as *const u8 as usize ),* ] }
        }
    };
}

isr_stubs!(
    isr_0, isr_1, isr_2, isr_3, isr_4, isr_5, isr_6, isr_7,
    isr_8, isr_9, isr_10, isr_11, isr_12, isr_13, isr_14, isr_15,
    isr_16, isr_17, isr_18, isr_19, isr_20, isr_21, isr_22, isr_23,
    isr_24, isr_25, isr_26, isr_27, isr_28, isr_29, isr_30, isr_31,
    isr_32, isr_33, isr_34, isr_35, isr_36, isr_37, isr_38, isr_39,
    isr_40, isr_41, isr_42, isr_43, isr_44, isr_45, isr_46, isr_47,
);

pub fn set_handler(vector: u8, addr: usize) {
    unsafe {
        IDT.entries[vector as usize].set(addr);
    }
}

pub fn init() {
    for (vec, addr) in stub_addrs().into_iter().enumerate() {
        set_handler(vec as u8, addr);
    }
    unsafe {
        let p = Ptr {
            limit: core::mem::size_of::<Idt>() as u16 - 1,
            base: &raw const IDT as u64,
        };
        asm!("lidt [{}]", in(reg) &p as *const Ptr, options(nostack));
    }
}

// ---------------------------------------------------------------------------
// The Rust-side dispatcher
// ---------------------------------------------------------------------------

const EXC_NAMES: [&str; 32] = [
    "divide_error", "debug", "nmi", "breakpoint", "overflow", "bound_range",
    "invalid_opcode", "device_na", "double_fault", "coproc_seg", "invalid_tss",
    "seg_not_present", "stack_fault", "general_protection", "page_fault",
    "reserved_15", "x87_fpu", "alignment_check", "machine_check", "simd_fp",
    "virtualization", "cp_exception", "reserved_22", "reserved_23", "reserved_24",
    "reserved_25", "reserved_26", "reserved_27", "hv_injection", "vmm_comm",
    "security", "reserved_31",
];

#[no_mangle]
extern "C" fn common_handler(vec: u64, regs: &mut Regs) {
    match vec {
        0..=31 => {
            let name = EXC_NAMES[vec as usize];
            crate::klog!(
                "EXCEPTION {} rip={:#x} err={:#x} rflags={:#x}",
                name,
                regs.rip,
                regs.error_code,
                regs.rflags
            );
            if vec == 14 {
                let cr2: u64;
                unsafe { asm!("mov {}, cr2", out(reg) cr2, options(nomem, nostack, preserves_flags)) };
                crate::klog!("  page fault at cr2={:#x}", cr2);
            }
            fatal_exception(name);
        }
        32 => {
            pit::tick();
            unsafe { pic::eoi_master() };
        }
        33 => {
            keyboard::on_irq();
            unsafe { pic::eoi_master() };
        }
        39 => {
            if pic::isr_master_bit7() {
                unsafe { pic::eoi_master() };
            } else {
                crate::klog!("spurious irq7 ignored");
            }
        }
        47 => {
            if pic::isr_slave_bit7() {
                unsafe {
                    pic::eoi_slave();
                    pic::eoi_master();
                }
            } else {
                crate::klog!("spurious irq15 ignored");
            }
        }
        34..=46 => {
            crate::klog!("unexpected irq {}", vec - 32);
            unsafe { pic::eoi_master() };
        }
        _ => {
            crate::klog!("unexpected vector {}", vec);
            fatal_exception("unexpected_vector");
        }
    }
}

fn fatal_exception(name: &str) -> ! {
    crate::console::print_color("EXCEPTION: ", crate::console::GLM_RED);
    crate::console::print(name);
    crate::console::print(" - see serial log\n");
    loop {
        crate::io::ports::hlt();
    }
}
