//! Interrupt Descriptor Table + Rust interrupt dispatcher.
//!
//! Hand-written asm stubs (isr_stubs.S) push GP registers and call
//! `common_handler(vector, regs)`. This is stable-Rust friendly (no
//! nightly `abi_x86_interrupt`) and keeps full control in-house.

use core::arch::asm;

use super::apic;
use super::gdt;
use super::keyboard;
use super::pic;
use super::pit;

#[repr(C)]
pub struct Regs {
    // ⚠ order MUST mirror PUSH_GPRS in isr_stubs.S: rax is pushed FIRST,
    // so it lands at the highest GP slot; r15 (pushed last) is at [rsp+0].
    // Reading these fields in the wrong order silently aliases registers —
    // v0.1 got away with it because only rip/error_code were ever read.
    pub r15: u64,
    pub r14: u64,
    pub r13: u64,
    pub r12: u64,
    pub r11: u64,
    pub r10: u64,
    pub r9: u64,
    pub r8: u64,
    pub rbp: u64,
    pub rdi: u64,
    pub rsi: u64,
    pub rdx: u64,
    pub rcx: u64,
    pub rbx: u64,
    pub rax: u64,
    // pushed by stub after GP regs:
    pub error_code: u64,
    pub rip: u64,
    pub cs: u64,
    pub rflags: u64,
    pub rsp: u64,
    pub ss: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Entry {
    off_lo: u16,
    sel: u16,
    ist: u8,
    attr: u8,
    off_mid: u16,
    off_hi: u32,
    rsv: u32,
}

impl Entry {
    const MISSING: Entry = Entry {
        off_lo: 0,
        sel: 0,
        ist: 0,
        attr: 0,
        off_mid: 0,
        off_hi: 0,
        rsv: 0,
    };

    fn set(&mut self, handler: usize) {
        self.set_ex(handler, 0, 0);
    }

    /// Full control: DPL (gate callable from ring N) and IST stack index.
    fn set_ex(&mut self, handler: usize, dpl: u8, ist: u8) {
        *self = Entry {
            off_lo: handler as u16,
            sel: gdt::KERNEL_CODE,
            ist,
            attr: 0x8E | ((dpl as u8) << 5), // present, ring{dpl}, interrupt gate
            off_mid: (handler >> 16) as u16,
            off_hi: (handler >> 32) as u32,
            rsv: 0,
        };
    }
}

#[repr(C, align(16))]
struct Idt {
    entries: [Entry; 256],
}

static mut IDT: Idt = Idt {
    entries: [Entry::MISSING; 256],
};

#[repr(C, packed(2))]
struct Ptr {
    limit: u16,
    base: u64,
}

// stub symbols generated by isr_stubs.S: (vector, address) pairs in order.
// Vectors 0..=47 come first, then the syscall gate at 128.
macro_rules! isr_stubs {
    ($($vec:literal => $sym:ident),* $(,)?) => {
        extern "C" {
            $(static $sym: u8;)*
        }
        fn stub_addrs() -> [(u8, usize); 51] {
            unsafe { [ $( ($vec, &$sym as *const u8 as usize) ),* ] }
        }
    };
}

isr_stubs!(
    0 => isr_0, 1 => isr_1, 2 => isr_2, 3 => isr_3,
    4 => isr_4, 5 => isr_5, 6 => isr_6, 7 => isr_7,
    8 => isr_8, 9 => isr_9, 10 => isr_10, 11 => isr_11,
    12 => isr_12, 13 => isr_13, 14 => isr_14, 15 => isr_15,
    16 => isr_16, 17 => isr_17, 18 => isr_18, 19 => isr_19,
    20 => isr_20, 21 => isr_21, 22 => isr_22, 23 => isr_23,
    24 => isr_24, 25 => isr_25, 26 => isr_26, 27 => isr_27,
    28 => isr_28, 29 => isr_29, 30 => isr_30, 31 => isr_31,
    32 => isr_32, 33 => isr_33, 34 => isr_34, 35 => isr_35,
    36 => isr_36, 37 => isr_37, 38 => isr_38, 39 => isr_39,
    40 => isr_40, 41 => isr_41, 42 => isr_42, 43 => isr_43,
    44 => isr_44, 45 => isr_45, 46 => isr_46, 47 => isr_47,
    96 => isr_96,
    128 => isr_128,
    255 => isr_255,
);

pub fn set_handler(vector: u8, addr: usize) {
    unsafe {
        IDT.entries[vector as usize].set(addr);
    }
}

/// Handler callable from ring 3 (e.g. the int 0x80 syscall gate).
pub fn set_handler_user(vector: u8, addr: usize) {
    unsafe {
        IDT.entries[vector as usize].set_ex(addr, 3, 0);
    }
}

/// Handler on a dedicated IST stack (survives stack corruption).
pub fn set_handler_ist(vector: u8, addr: usize, ist: u8) {
    unsafe {
        IDT.entries[vector as usize].set_ex(addr, 0, ist);
    }
}

pub fn init() {
    for (vec, addr) in stub_addrs() {
        match vec {
            8 => set_handler_ist(8, addr, 1),   // double fault -> IST1
            128 => set_handler_user(128, addr), // syscall gate (ring 3)
            _ => set_handler(vec, addr),
        }
    }
    unsafe {
        let p = Ptr {
            limit: core::mem::size_of::<Idt>() as u16 - 1,
            base: &raw const IDT as u64,
        };
        asm!("lidt [{}]", in(reg) &p as *const Ptr, options(nostack));
    }
}

// ---------------------------------------------------------------------------
// The Rust-side dispatcher
// ---------------------------------------------------------------------------

const EXC_NAMES: [&str; 32] = [
    "divide_error", "debug", "nmi", "breakpoint", "overflow", "bound_range",
    "invalid_opcode", "device_na", "double_fault", "coproc_seg", "invalid_tss",
    "seg_not_present", "stack_fault", "general_protection", "page_fault",
    "reserved_15", "x87_fpu", "alignment_check", "machine_check", "simd_fp",
    "virtualization", "cp_exception", "reserved_22", "reserved_23", "reserved_24",
    "reserved_25", "reserved_26", "reserved_27", "hv_injection", "vmm_comm",
    "security", "reserved_31",
];

const SYS_VECTOR: u64 = 128;
const LAPIC_TIMER_VECTOR: u64 = crate::cpu::apic::TIMER_VECTOR as u64;

/// The one true dispatcher. Returns either null (resume the interrupted
/// context) or the Regs frame of the NEXT task to run — the asm stub then
/// moves rsp there and iretqs into it: a complete context switch.
#[no_mangle]
extern "C" fn common_handler(vec: u64, regs: &mut Regs) -> *mut Regs {
    let from_user = regs.cs & 0x3 != 0;
    match vec {
        0..=31 => {
            let name = EXC_NAMES[vec as usize];
            if from_user {
                // user task faulted: kill the task, never the kernel.
                // fault_and_terminate marks it zombie and requests a switch;
                // execution falls through to post_dispatch below, which
                // hands the CPU to someone else (the faulting frame is
                // abandoned — there is no way back to ring 3 here).
                if vec == 14 {
                    let cr2: u64;
                    unsafe { asm!("mov {}, cr2", out(reg) cr2, options(nomem, nostack, preserves_flags)) };
                    crate::user::task::fault_and_terminate(
                        "page fault",
                        format_args!("address {:#x}, rip {:#x}, error {:#010b} ({}{}{})",
                            cr2, regs.rip, regs.error_code,
                            if regs.error_code & 1 != 0 { "prot-violation" } else { "not-present" },
                            if regs.error_code & 2 != 0 { ", write" } else { ", read" },
                            if regs.error_code & 4 != 0 { ", user-mode" } else { "" }),
                    );
                } else {
                    crate::user::task::fault_and_terminate(
                        name,
                        format_args!("rip {:#x}", regs.rip),
                    );
                }
            } else {
                // kernel fault: log everything and stop
                if vec == 14 {
                    let cr2: u64;
                    unsafe { asm!("mov {}, cr2", out(reg) cr2, options(nomem, nostack, preserves_flags)) };
                    crate::klog!("page fault at cr2={:#x}", cr2);
                }
                crate::klog!(
                    "EXCEPTION {} rip={:#x} err={:#x} rflags={:#x} user={}",
                    name,
                    regs.rip,
                    regs.error_code,
                    regs.rflags,
                    from_user
                );
                fatal_exception(name);
            }
        }
        32 => {
            pit::tick();
            unsafe { pic::eoi_master() };
            apic::eoi();
        }
        33 => {
            keyboard::on_irq();
            unsafe { pic::eoi_master() };
            apic::eoi();
        }
        39 => {
            if pic::isr_master_bit7() {
                unsafe { pic::eoi_master() };
            } else {
                crate::klog!("spurious irq7 ignored");
            }
            apic::eoi();
        }
        47 => {
            if pic::isr_slave_bit7() {
                unsafe {
                    pic::eoi_slave();
                    pic::eoi_master();
                }
            } else {
                crate::klog!("spurious irq15 ignored");
            }
            apic::eoi();
        }
        34..=46 => {
            crate::klog!("unexpected irq {}", vec - 32);
            unsafe { pic::eoi_master() };
            apic::eoi();
        }
        LAPIC_TIMER_VECTOR => {
            // scheduler heartbeat: EOI only (wake-ups + preemption decision
            // happen in post_dispatch below)
            apic::eoi();
        }
        SYS_VECTOR => {
            crate::user::syscall::dispatch(regs);
        }
        97..=254 => {
            crate::klog!("unexpected apic vector {:#x}", vec);
            apic::eoi();
        }
        255 => {
            // spurious LAPIC interrupt: must NOT be EOIed
        }
        _ => {
            crate::klog!("unexpected vector {}", vec);
            fatal_exception("unexpected_vector");
        }
    }

    // unified switch epilogue: timer wake-ups, preemption, yields, exits.
    // Returns null (stay) or another task's frame (switch in the stub).
    crate::sched::post_dispatch(vec, regs)
}

fn fatal_exception(name: &str) -> ! {
    crate::console::print_color("EXCEPTION: ", crate::console::GLM_RED);
    crate::console::print(name);
    crate::console::print(" - see serial log\n");
    loop {
        crate::io::ports::hlt();
    }
}
